---
- name: Converge
  hosts: all
  become: true

  vars:
    ntpsec_client_service_name: 'ntpsec'
    ntpsec_client_config_file: '/etc/ntpsec/ntp.conf'
    ntpsec_client_config_dir: '/etc/ntpsec/ntp.d'
    ntpsec_client_drift_file: '/var/lib/ntpsec/ntp.drift'
    ntpsec_cleanup_systemd_timesyncd: false

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - role: sh.ntpsec
